### ISSUE TITLE
Dokumente können nicht geöffnet werden

### ISSUE THREAD

**Issue by prueggpebe** [swico/ebill-swp-api#10]
Die hier publizierten Dokumente, sowohl docx wie auch pdf können zwar heruntergeladen, aber nicht geöffnet werden: "Kein pdf-Format oder beschädigtes Dokument" beim pdf, "die Datei ist beschädigt und kann nicht geöffnet werden"

[SchnittstellenempfehlungSIXeBill.docx](https://github.com/swico/ebill-swp-api/files/4971582/SchnittstellenempfehlungSIXeBill.docx)
[SchnittstellenempfehlungSIXeBill-DRAFT-0.6.pdf](https://github.com/swico/ebill-swp-api/files/4971583/SchnittstellenempfehlungSIXeBill-DRAFT-0.6.pdf)
[InterfaceRecommendationSIXeBill.docx](https://github.com/swico/ebill-swp-api/files/4971584/InterfaceRecommendationSIXeBill.docx)

 beim docx.

**Comment by EvaSediki** [comment]
Es gibt seit 2 Wochen neue Dokumente (DRAFT  0.7) im Verzeichnis [documents](https://github.com/swico/ebill-swp-api/tree/master/documents); ich kann dort alle Dateien herunterladen und öffnen.

**Comment by prueggpebe** [comment]
Wenn ich das pdf Dokument im Browser mit Linksklick öffne, wird das pdf angezeigt. Wenn ich es mit rechter Maustaste "Ziel speichern" runterziehe, hat es Fehler.
