### ISSUE TITLE
Branchen

### ISSUE THREAD

**Issue by fabio-martinetti** [swico/ebill-swp-api#12]
SWP-Partner, die das eBill-Onboarding der Rechnungssteller implementieren möchten, benötigen die Liste der Branchen. 
Kann das SWP-API um den GET /sectors Request erweitert werden, analog zum NWP-API?

**Comment by nicolasguillet** [comment]
Finde ich eine gute Idee, werde das für das nächste Core-Treffen traktandieren.

**Comment by nicolasguillet** [comment]
Entscheid Core-Gruppe: Wird umgesetzt.
