### ISSUE TITLE
Document statt BusinessCase

### ISSUE THREAD

**Issue by fabio-martinetti** [swico/ebill-swp-api#13]
Generell sollte auf den Ausdruck «Business Case» verzichtet werden. Der Ausdruck ist historisch bedingt aus der falschen Übersetzung von «Geschäftsvorfall» entstanden und hat eine völlig andere Bedeutung als hier gemeint ist. Vielleicht könnte man stattdessen «Document» oder «InvoiceDocument» verwenden.

**Comment by nicolasguillet** [comment]
Ja der Ausdruck ist nicht ideal, wir haben ihn aber vom NWP-API "geerbt", dort ist er überall drin. Deshalb würde ich meinen, es ist besser, es zu belassen wie es ist.

**Comment by nicolasguillet** [comment]
Entscheid Core-Gruppe: Zu aufwendig, würde zu Inkonsistenzen führen.
