### ISSUE TITLE
DokRef statt NWPBCID

### ISSUE THREAD

**Issue by fabio-martinetti** [swico/ebill-swp-api#14]
Beim Create BusinessCase-Request wird eine neue Referenz der Rechnung an den SWP zurückgegeben ("id": "NWPBCID0FB909852BBC4D06AD8336AAE87D7FC9"), die später in den Get BusinessCase-Requests oder in den Events wiederverwendet wird.

Warum wird eine neue Referenz vergeben statt die Rechnungsnummer (Dokument-Referenz) zu verwenden, die ja für einen Rechnungssteller eindeutig ist? Wenn die Dokument-Referenz verwendet würde, müsste auf Seiten des SWP kein neues Feld definiert werden, das ohnehin keinen Mehrwert bringt.

**Comment by nicolasguillet** [comment]
Ob die gleichen Rechnungsnummern in gewissen Fällen nicht doch doppelt vorkommen können, ist fast schon ein Flame-War, aus dem wir uns lieber raushalten ;-) Jedenfalls gibt es Biller, welche auch Punkte und Slashes in der Rechnungsnummer drin haben (warum auch immer), diese Zeichen kollidieren mit dem, was im Pfad einer URL mitgegeben werden kann, ohne dass es sehr kompliziert wird.
