### ISSUE TITLE
Content im Path statt im Body

### ISSUE THREAD

**Issue by fabio-martinetti** [swico/ebill-swp-api#15]
Warum werden Daten, die zum Inhalt des Requests gehören, im POST URL-Pfad übergeben, wie z.B. billerPid und busnessCaseId? Wie steht es mit dem Schutz dieser Informationen, wenn diese im URL stehen?
Eine White-List mit zulässigen URLs lässt sich auf diese Weise nicht erstellen.

**Comment by nicolasguillet** [comment]
Da das API zwingend über HTTPS laufen muss, könnten diese Infos allenfalls in den Logs beim NWP erscheinen, sollten dort aber eigentlich nicht heikel sein, wobei natürlich alle Logs immer sehr gut geschützt werden müssen.
Dass diese Infos im Pfad erscheinen, ist in der DNA von REST drin, das sollte man eben so machen. Eine Whitelist ist so gesehen also nur auf Ebene Domäne oder allenfalls noch mit dem ersten oder den ersten beiden Segmenten des Pfades möglich, wobei ich persönlich empfehlen würde, bei REST generell nicht den Pfad zu prüfen.

**Comment by nicolasguillet** [comment]
Entscheid Core-Gruppe: Pfad wird belassen wie es ist, so ist REST nun mal.
