### ISSUE TITLE
RefreshToken mit unbestimmter Gültigkeitsdauer

### ISSUE THREAD

**Issue by EvaSediki** [swico/ebill-swp-api#3]
**SchnittstellenempfehlungSIXeBill DRAFT-0.6**

Wenn ich jetzt aus definierten Umständen kein   Refresh Token mehr habe, kann ich ja aber einfach wieder den Authorization   Flow ausführen oder? Möchte ja keine Tokens irgendwo persistieren müssen.   Finde auch die Empfehlung, dass Refresh-Tokens eine unbestimmte   Gültigkeitsdauer besitzen dürfen, fragwürdig. Eine maximale Gültigkeitsdauer   sollte schon vorgegeben werden. Ist ja eigentlich ein Passwort auf die API   (mit Refresh-Tokens kann ich wieder Access Tokens lösen, mit Access Tokens   kann ich die API verwenden.)

Eingereicht von Abraxas Informatik AG, am 18.5.2020

**Comment by nicolasguillet** [comment]
Ja das ist korrekt, der NWP kann dem Biller jederzeit ein neues Onboardin-JSON zustellen.

Die Frage wegen der unbestimmten Gültigkeitsdauer ist absolut berechtigt und wir werden das in der nächsten Core-Sitzung besprechen.

**Comment by nicolasguillet** [comment]
Entscheid Core-Arbeitsgruppe: Die entsprechenden Stellen in der Doku werden angepasst, Refresh-Tokens sollten nicht unbegrenzt gültig sein.
