### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#31]
Generell ist die Governance für diese SWP-API völlig unklar. Es muss  klar geregelt sein, wer Inhaber oder  Urheber  dieser API ist und wer welche Rechte und Pflichten daraus trägt.

**Comment by EvaSediki** [comment]
Der Inhaber und Urheber ist die Arbeitsgruppe SWP-API; die Rechte und Pflichten sind in der OpenAPI-Lizenz beschrieben.
