### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#32]
Wer ist die Gegenpartei? Beim wem könnte bspw. die Lizenz gekündigt werden, wie in Ziffer 5 beschrieben.

**Comment by nicolasguillet** [comment]
NWP und SWP können formell hier via Issue künden. In der Regel wird das aber gar nicht nötig sein, denn man kann einfach aufhören, das API zu verwenden und nicht mehr mit "Unterstützt das SIX eBill SWP API" Werbung machen.
