### ISSUE TITLE
S. 7; Authorization

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#36]
Wer unterstützt hier den NWP bei Problemen technischer Art.
Wo/wann wird definiert, ob Access-Token kein vordefiniertes Ablaufdatum hat ("wenn der NWP das wünscht…" steht).

**Comment by EvaSediki** [comment]
Probleme können hier in github gepostet werden.

**Comment by nicolasguillet** [comment]
Zweite Frage: Siehe Issue #3.
