### ISSUE TITLE
Doku für Accept Headers

### ISSUE THREAD

**Issue by EvaSediki** [swico/ebill-swp-api#4]
**Software Partner API v1, /billers/{billerPid}/business-cases/{businessCaseId}**

Die zu verwendeten Accept Headers sind nirgends beschrieben, oder habe ich diese überlesen?

Eingereicht von Abraxas Informatik AG, am 18.5.2020

**Comment by nicolasguillet** [comment]
Bin nicht sicher ob ich die Frage richtig verstehe, weil in der Doku ist jeweils drin:

Accept: application/json

**Comment by EvaSediki** [comment]
In der Swagger-Datei (swp-nwp-api-v*-swagger.yaml) steht bei jeder Operation, welcher Content-Type zurückgegeben wird bzw. werden kann, z.B.
`operationId:getBusinessCase` 
`produces:` 
`        - application/json` 
`        - application/pdf` 
Der Anrufer kann einen dieser Content-Types im Accept-Header angeben, z.B. `-H  "accept: application/json"`.
