### ISSUE TITLE
S. 4; Einlieferformate

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#40]
Es macht sicherlich Sinn sich auf wenige oder im Idealfall auf 1 Austauschformat zu einigen. Hier wird aber erwartet das der NWP mit 4 Formaten umgehen können muss. Den SWP wird freigestellt welches Format sie verwenden. Der Aufwand wird an die NWP delegiert.

**Comment by nicolasguillet** [comment]
Genau das ist die Idee. Die wenigen NWP sollen den Aufwand haben, die ca. 100 Softwarehersteller, für welche dieses API gedacht ist, dafür nicht. Für NWPs ist die Umsetzung dieser API-Empfehlung freiwillig, sie können auch mit den bestehenden APIs und Formaten weiter arbeiten, wenn das für sie von Vorteil ist.
