### ISSUE TITLE
S. 12; B2B-Meldungen zwischen NWPs

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#44]
"Mit dem bcFormat-Headerfeld kann der SWP festlegen, welches Format er empfangen will. Ein PDF wird in allen Fällen mit ausgeliefert."
Anmerkung: Das Format kann nur vorgängig pro Payer festgelegt und nur in Absprache mit dem NWP geändert werden. 
Warum ist hier von Payer die Rede?

**Comment by nicolasguillet** [comment]
Gemeint ist hier der Empfang von B2B Rechnungen, gilt nur für NWPs, welche das optionale B2B unterstützen. In diesen Fällen kann der SWP wählen, welches Format er empfangen will.
