### ISSUE TITLE
S. 4; B2B-Meldungen zwischen NWPs

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#45]
"Der Softwarehersteller sollte beim Einliefern der Rechnung das Header-Feld «bcFormat» mitgeben, um dem NWP mitzuteilen, in welchem Format die Rechnung vorliegt."
Anmerkung: Das Format kann nur vorgängig pro Biller  festgelegt und nur in Absprache mit dem NWP geändert werden.

**Comment by nicolasguillet** [comment]
Die Idee dieses REST-APIs ist, dass ein Biller jedes der zugelassenen Formate verwenden kann, im Extremfall sogar abwechslungsweise, weil der NWP ja eh alle unterstützen muss, wenn er dieses API implementiert.
