### ISSUE TITLE
B2B-Meldungen zwischen NWPs

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#46]
"SWPs, welche auch Rechnungen empfangen können, können die entsprechenden Endpoints aufrufen"
Heisst, dass der NWP Rechnungen parkieren müsste. Dadurch entstehen für den NWP mit grosser Wahrscheinlichkeit Supportaufwände für den Fall das Rechnungen nochmals bereitgestellt werden müssen weil das abholen nicht funktioniert oder ähnliches.

**Comment by nicolasguillet** [comment]
Genau so ist es, der NWP kann dafür vom Empfänger eine Gebühr verlangen.
