### ISSUE TITLE
Protokolle

### ISSUE THREAD

**Issue by susanneLauper** [swico/ebill-swp-api#47]
Das Thema Weiterleitung von Events wurde gar nicht angesprochen. Wie werden Verarbeitungsmeldungen zurückgegeben?

**Comment by EvaSediki** [comment]
Events, die der NWP von SIX bekommt, werden dem SWP nach dem gleichen Mechanismus wie im NWP-API zur Verfügung gestellt. Die Events sollen aber nur dem SWP des Billers gegeben werden, für den das Event erzeugt wurde. 
Der NWP kann selbst weitere Verarbeitungsevents der bisher definierten Typen erzeugen und an den SWP zurückgeben.

Werden Ihrer Meinung nach noch andere Event-Typen gebraucht?
