### ISSUE TITLE
Produktiv?

### ISSUE THREAD

**Issue by prueggpebe** [swico/ebill-swp-api#50]
Hallo
Gibt es schon Netzwerkpartner, welche die API produktiv am Laufen haben oder wann ist der produktive Einsatz geplant? Gibt es eine Testplattform, wo man eine Umsetzung der API testen könnte? Wir planen unseren nächsten Softwarerelease und die API-Anbindung ist eine mögliche Erweiterung, die wir umsetzen könnten. Da wir aber gebrannte Kinder sind - wir hatten z.B. bereits den QR-Einzahlungsschein fertig programmier, als dieser zur QR-Rechnung umfunktioniert wurde - möchten wir natürlich nicht unsere Entwicklungsressourcen in einem zu frühen Stadion investieren. Unsere Entwicklungskapazitäten sind leider begrenzt und der Projekte vieler...

Danke für die Info

**Comment by nicolasguillet** [comment]
Es gibt neu eine Status-Seite der NWPs:
https://github.com/swico/ebill-swp-api/blob/master/documents/nwpstatus.md
Das API ist in der Version 1.0 released und bereits implementiert. Vorläufig sind keine Änderungen geplant, aber natürlich wird es mal eine Version 1.1 und 2.0 geben
