### ISSUE TITLE
Segmentierung der Events

### ISSUE THREAD

**Issue by EvaSediki** [swico/ebill-swp-api#9]
**Software Partner API v1, /events/business-case-status-changed**

API-Design: will man die Events nicht logischer segmentieren? Macht das für die Zukunft ggf. Sinn?
- /events/business-case/
- /events/instalment/
- /events/bill-recipient/email/
- /events/bill-recipient/subscription/

Eingereicht von Abraxas Informatik AG, am 18.5.2020

**Comment by nicolasguillet** [comment]
Diese Events wurden vom SIX NWP API "vererbt", also der Schnittstelle zwischen den NWP und SIX eBill. Diese ist bereits produktiv, der Aufwand also recht hoch, das jetzt noch zu ändern. Falls das jemand unbedingt wünscht, können wir es in der Core-Arbeitsgruppe besprechen.
